services:
  backend:
    build: .
    image: buchungssystem:latest
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  frontend:
    build: .
    image: buchungssystem:latest
    command: streamlit run frontend/app.py --server.address=0.0.0.0 --server.port=8501 --server.headless=true
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app/frontend
      - ./.streamlit:/app/.streamlit
    depends_on:
      - backend